$(document).ready(function() {

  var lcrc = document.getElementById("lcrc")
  var lcrcpdf = document.getElementById("lcrcpdf")
  var demon = document.getElementById("demon")
  var demonpdf = document.getElementById("demonpdf")
  var ramraid = document.getElementById("ramraid")
  var ramraidpdf = document.getElementById("ramraidpdf")
  var special = document.getElementById("special")
  var specialpdf = document.getElementById("specialpdf")
  var diver = document.getElementById("diver")
  var diverpdf = document.getElementById("diverpdf")
  var untimed = document.getElementById("untimed")
  var untimedpdf = document.getElementById("untimedpdf")
  var cruciform = document.getElementById("cruciform")
  var cruciformpdf = document.getElementById("cruciformpdf")
  var attendants = document.getElementById("attendants")
  var attendantspdf = document.getElementById("attendantspdf")
  var current = document.getElementById("current")
  var contact = document.getElementById("contact")
  var email = document.getElementById("email")
  var louismason = document.getElementById("louismason")
  var horror = document.getElementById("horror")
  var horrorimg = document.getElementById("horrorimg")
  var gradshow = document.getElementById("gradshow")
  var gradshowimg = document.getElementById("gradshowimg")
  var villages = document.getElementById("villages")
  var villagesimg = document.getElementById("villagesimg")
  var future = document.getElementById("future")
  var futureimg = document.getElementById("futureimg")
  var share = document.getElementById("share")
  var shareimg = document.getElementById("shareimg")
  var gog = document.getElementById("gog")
  var gogimg = document.getElementById("gogimg")
  var body = document.getElementById("body")
  var bodyimg = document.getElementById("bodyimg")
  var summit = document.getElementById("summit")
  var summitimg = document.getElementById("summitimg")
  var desert = document.getElementById("desert")
  var desertimg = document.getElementById("desertimg")

  louismason.onclick = function() {
    current.style.display = "block";
    lcrcpdf.style.display = "none";
    demonpdf.style.display = "none";
    ramraidpdf.style.display = "none";
    specialpdf.style.display = "none";
    diverpdf.style.display = "none";
    untimedpdf.style.display = "none";
    cruciformpdf.style.display = "none";
    attendantspdf.style.display = "none";
    email.style.display = "none";
    horrorimg.style.display = "none";
    gradshowimg.style.display = "none";
    villagesimg.style.display = "none";
    futureimg.style.display = "none";
    shareimg.style.display = "none";
    gogimg.style.display = "none";
    bodyimg.style.display = "none";
    summitimg.style.display = "none";
    desertimg.style.display = "none";
  }

  lcrc.onclick = function() {
      current.style.display = "none";
      lcrcpdf.style.display = "block";
      demonpdf.style.display = "none";
      ramraidpdf.style.display = "none";
      specialpdf.style.display = "none";
      diverpdf.style.display = "none";
      untimedpdf.style.display = "none";
      cruciformpdf.style.display = "none";
      attendantspdf.style.display = "none";
      email.style.display = "none";
      horrorimg.style.display = "none";
      gradshowimg.style.display = "none";
      villagesimg.style.display = "none";
      futureimg.style.display = "none";
      shareimg.style.display = "none";
      gogimg.style.display = "none";
      bodyimg.style.display = "none";
      summitimg.style.display = "none";
      desertimg.style.display = "none";
    }

  demon.onclick = function() {
      current.style.display = "none";
      demonpdf.style.display = "block";
      lcrcpdf.style.display = "none";
      ramraidpdf.style.display = "none";
      specialpdf.style.display = "none";
      diverpdf.style.display = "none";
      untimedpdf.style.display = "none";
      cruciformpdf.style.display = "none";
      attendantspdf.style.display = "none";
      email.style.display = "none";
      horrorimg.style.display = "none";
      villagesimg.style.display = "none";
      futureimg.style.display = "none";
      shareimg.style.display = "none";
      gogimg.style.display = "none";
      bodyimg.style.display = "none";
      summitimg.style.display = "none";
      desertimg.style.display = "none";
    }

  ramraid.onclick = function() {
      current.style.display = "none";
      ramraidpdf.style.display = "block";
      demonpdf.style.display = "none";
      lcrcpdf.style.display = "none";
      specialpdf.style.display = "none";
      diverpdf.style.display = "none";
      untimedpdf.style.display = "none";
      cruciformpdf.style.display = "none";
      attendantspdf.style.display = "none";
      email.style.display = "none";
      horrorimg.style.display = "none";
      gradshowimg.style.display = "none";
      villagesimg.style.display = "none";
      futureimg.style.display = "none";
      shareimg.style.display = "none";
      gogimg.style.display = "none";
      bodyimg.style.display = "none";
      summitimg.style.display = "none";
      desertimg.style.display = "none";
    }

  contact.onclick = function() {
      email.style.display = "block";
      current.style.display = "none";
      ramraidpdf.style.display = "none";
      demonpdf.style.display = "none";
      lcrcpdf.style.display = "none";
      specialpdf.style.display = "none";
      diverpdf.style.display = "none";
      untimedpdf.style.display = "none";
      cruciformpdf.style.display = "none";
      attendantspdf.style.display = "none";
      horrorimg.style.display = "none";
      gradshowimg.style.display = "none";
      villagesimg.style.display = "none";
      futureimg.style.display = "none";
      shareimg.style.display = "none";
      gogimg.style.display = "none";
      bodyimg.style.display = "none";
      summitimg.style.display = "none";
      desertimg.style.display = "none";
    }

    horror.onclick = function() {
        horrorimg.style.display = "block";
        email.style.display = "none";
        current.style.display = "none";
        ramraidpdf.style.display = "none";
        demonpdf.style.display = "none";
        lcrcpdf.style.display = "none";
        specialpdf.style.display = "none";
        diverpdf.style.display = "none";
        untimedpdf.style.display = "none";
        cruciformpdf.style.display = "none";
        attendantspdf.style.display = "none";
        gradshowimg.style.display = "none";
        villagesimg.style.display = "none";
        futureimg.style.display = "none";
        shareimg.style.display = "none";
        gogimg.style.display = "none";
        bodyimg.style.display = "none";
        summitimg.style.display = "none";
        desertimg.style.display = "none";
      }

    gradshow.onclick = function() {
        gradshowimg.style.display = "block";
        email.style.display = "none";
        current.style.display = "none";
        ramraidpdf.style.display = "none";
        demonpdf.style.display = "none";
        lcrcpdf.style.display = "none";
        specialpdf.style.display = "none";
        diverpdf.style.display = "none";
        untimedpdf.style.display = "none";
        cruciformpdf.style.display = "none";
        attendantspdf.style.display = "none";
        horrorimg.style.display = "none";
        villagesimg.style.display = "none";
        futureimg.style.display = "none";
        shareimg.style.display = "none";
        gogimg.style.display = "none";
        bodyimg.style.display = "none";
        summitimg.style.display = "none";
        desertimg.style.display = "none";
      }

      villages.onclick = function() {
          gradshowimg.style.display = "none";
          email.style.display = "none";
          current.style.display = "none";
          ramraidpdf.style.display = "none";
          demonpdf.style.display = "none";
          lcrcpdf.style.display = "none";
          specialpdf.style.display = "none";
          diverpdf.style.display = "none";
          untimedpdf.style.display = "none";
          cruciformpdf.style.display = "none";
          attendantspdf.style.display = "none";
          horrorimg.style.display = "none";
          villagesimg.style.display = "block";
          futureimg.style.display = "none";
          shareimg.style.display = "none";
          gogimg.style.display = "none";
          bodyimg.style.display = "none";
          summitimg.style.display = "none";
          desertimg.style.display = "none";
        }

        future.onclick = function() {
            gradshowimg.style.display = "none";
            email.style.display = "none";
            current.style.display = "none";
            ramraidpdf.style.display = "none";
            demonpdf.style.display = "none";
            lcrcpdf.style.display = "none";
            specialpdf.style.display = "none";
            diverpdf.style.display = "none";
            untimedpdf.style.display = "none";
            cruciformpdf.style.display = "none";
            attendantspdf.style.display = "none";
            horrorimg.style.display = "none";
            villagesimg.style.display = "none";
            futureimg.style.display = "block";
            shareimg.style.display = "none";
            gogimg.style.display = "none";
            bodyimg.style.display = "none";
            summitimg.style.display = "none";
            desertimg.style.display = "none";
          }

          share.onclick = function() {
              gradshowimg.style.display = "none";
              email.style.display = "none";
              current.style.display = "none";
              ramraidpdf.style.display = "none";
              demonpdf.style.display = "none";
              lcrcpdf.style.display = "none";
              specialpdf.style.display = "none";
              diverpdf.style.display = "none";
              untimedpdf.style.display = "none";
              cruciformpdf.style.display = "none";
              attendantspdf.style.display = "none";
              horrorimg.style.display = "none";
              villagesimg.style.display = "none";
              futureimg.style.display = "none";
              shareimg.style.display = "block";
              gogimg.style.display = "none";
              bodyimg.style.display = "none";
              summitimg.style.display = "none";
              desertimg.style.display = "none";
            }

            special.onclick = function() {
                gradshowimg.style.display = "none";
                email.style.display = "none";
                current.style.display = "none";
                ramraidpdf.style.display = "none";
                demonpdf.style.display = "none";
                lcrcpdf.style.display = "none";
                specialpdf.style.display = "block";
                diverpdf.style.display = "none";
                untimedpdf.style.display = "none";
                cruciformpdf.style.display = "none";
                attendantspdf.style.display = "none";
                horrorimg.style.display = "none";
                villagesimg.style.display = "none";
                futureimg.style.display = "none";
                shareimg.style.display = "none";
                gogimg.style.display = "none";
                bodyimg.style.display = "none";
                summitimg.style.display = "none";
                desertimg.style.display = "none";
              }

              diver.onclick = function() {
                  gradshowimg.style.display = "none";
                  email.style.display = "none";
                  current.style.display = "none";
                  ramraidpdf.style.display = "none";
                  demonpdf.style.display = "none";
                  lcrcpdf.style.display = "none";
                  specialpdf.style.display = "none";
                  diverpdf.style.display = "block";
                  untimedpdf.style.display = "none";
                  cruciformpdf.style.display = "none";
                  attendantspdf.style.display = "none";
                  horrorimg.style.display = "none";
                  villagesimg.style.display = "none";
                  futureimg.style.display = "none";
                  shareimg.style.display = "none";
                  gogimg.style.display = "none";
                  bodyimg.style.display = "none";
                  summitimg.style.display = "none";
                  desertimg.style.display = "none";
                }

              gog.onclick = function() {
                  gradshowimg.style.display = "none";
                  email.style.display = "none";
                  current.style.display = "none";
                  ramraidpdf.style.display = "none";
                  demonpdf.style.display = "none";
                  lcrcpdf.style.display = "none";
                  specialpdf.style.display = "none";
                  diverpdf.style.display = "none";
                  untimedpdf.style.display = "none";
                  cruciformpdf.style.display = "none";
                  attendantspdf.style.display = "none";
                  horrorimg.style.display = "none";
                  villagesimg.style.display = "none";
                  futureimg.style.display = "none";
                  shareimg.style.display = "none";
                  gogimg.style.display = "block";
                  bodyimg.style.display = "none";
                  summitimg.style.display = "none";
                  desertimg.style.display = "none";
                }

                body.onclick = function() {
                    gradshowimg.style.display = "none";
                    email.style.display = "none";
                    current.style.display = "none";
                    ramraidpdf.style.display = "none";
                    demonpdf.style.display = "none";
                    lcrcpdf.style.display = "none";
                    specialpdf.style.display = "none";
                    diverpdf.style.display = "none";
                    untimedpdf.style.display = "none";
                    attendantspdf.style.display = "none";
                    cruciformpdf.style.display = "none";
                    horrorimg.style.display = "none";
                    villagesimg.style.display = "none";
                    futureimg.style.display = "none";
                    shareimg.style.display = "none";
                    gogimg.style.display = "none";
                    bodyimg.style.display = "block";
                    summitimg.style.display = "none";
                    desertimg.style.display = "none";
                  }

                  untimed.onclick = function() {
                      gradshowimg.style.display = "none";
                      email.style.display = "none";
                      current.style.display = "none";
                      ramraidpdf.style.display = "none";
                      demonpdf.style.display = "none";
                      lcrcpdf.style.display = "none";
                      specialpdf.style.display = "none";
                      diverpdf.style.display = "none";
                      untimedpdf.style.display = "block";
                      cruciformpdf.style.display = "none";
                      attendantspdf.style.display = "none";
                      horrorimg.style.display = "none";
                      villagesimg.style.display = "none";
                      futureimg.style.display = "none";
                      shareimg.style.display = "none";
                      gogimg.style.display = "none";
                      bodyimg.style.display = "none";
                      summitimg.style.display = "none";
                      desertimg.style.display = "none";
                    }

                 cruciform.onclick = function() {
                      gradshowimg.style.display = "none";
                      email.style.display = "none";
                      current.style.display = "none";
                      ramraidpdf.style.display = "none";
                      demonpdf.style.display = "none";
                      lcrcpdf.style.display = "none";
                      specialpdf.style.display = "none";
                      diverpdf.style.display = "none";
                      untimedpdf.style.display = "none";
                      cruciformpdf.style.display = "block";
                      attendantspdf.style.display = "none";
                      horrorimg.style.display = "none";
                      villagesimg.style.display = "none";
                      futureimg.style.display = "none";
                      shareimg.style.display = "none";
                      gogimg.style.display = "none";
                      bodyimg.style.display = "none";
                      summitimg.style.display = "none";
                      desertimg.style.display = "none";
                    }

                attendants.onclick = function() {
                      gradshowimg.style.display = "none";
                      email.style.display = "none";
                      current.style.display = "none";
                      ramraidpdf.style.display = "none";
                      demonpdf.style.display = "none";
                      lcrcpdf.style.display = "none";
                      specialpdf.style.display = "none";
                      diverpdf.style.display = "none";
                      untimedpdf.style.display = "none";
                      cruciformpdf.style.display = "none";
                      attendantspdf.style.display = "block";
                      horrorimg.style.display = "none";
                      villagesimg.style.display = "none";
                      futureimg.style.display = "none";
                      shareimg.style.display = "none";
                      gogimg.style.display = "none";
                      bodyimg.style.display = "none";
                      summitimg.style.display = "none";
                      desertimg.style.display = "none";
                    }

                summit.onclick = function() {
                      gradshowimg.style.display = "none";
                      email.style.display = "none";
                      current.style.display = "none";
                      ramraidpdf.style.display = "none";
                      demonpdf.style.display = "none";
                      lcrcpdf.style.display = "none";
                      specialpdf.style.display = "none";
                      diverpdf.style.display = "none";
                      untimedpdf.style.display = "none";
                      cruciformpdf.style.display = "none";
                      attendantspdf.style.display = "none";
                      horrorimg.style.display = "none";
                      villagesimg.style.display = "none";
                      futureimg.style.display = "none";
                      shareimg.style.display = "none";
                      gogimg.style.display = "none";
                      bodyimg.style.display = "none";
                      summitimg.style.display = "block";
                      desertimg.style.display = "none";
                    }

                desert.onclick = function() {
                      gradshowimg.style.display = "none";
                      email.style.display = "none";
                      current.style.display = "none";
                      ramraidpdf.style.display = "none";
                      demonpdf.style.display = "none";
                      lcrcpdf.style.display = "none";
                      specialpdf.style.display = "none";
                      diverpdf.style.display = "none";
                      untimedpdf.style.display = "none";
                      cruciformpdf.style.display = "none";
                      attendantspdf.style.display = "none";
                      horrorimg.style.display = "none";
                      villagesimg.style.display = "none";
                      futureimg.style.display = "none";
                      shareimg.style.display = "none";
                      gogimg.style.display = "none";
                      bodyimg.style.display = "none";
                      summitimg.style.display = "none";
                      desertimg.style.display = "block";
                    }

})
